-- AlterTable
ALTER TABLE "accounts" ALTER COLUMN "balance" DROP DEFAULT,
ALTER COLUMN "balance" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "transactions" ALTER COLUMN "value" SET DATA TYPE DOUBLE PRECISION;
